#!/bin/sh

BASE_DIR=$(dirname $(dirname $(readlink -f ${0})))

INCLUDE_NAME="wssl.h"
LIBRARY_NAME="libwssl.a"
INCLUDE_FILE="${BASE_DIR}/out/${INCLUDE_NAME}"
LIBRARY_FILE="${BASE_DIR}/out/${LIBRARY_NAME}"
LIBRARY_ORGIN="${BASE_DIR}/source/${LIBRARY_NAME}"

function include_filter()
{
  awk -f ${BASE_DIR}/tool/awk/make_out_include.awk
}

function include_exec()
{
  gcc -E -P -I {BASE_DIR}/include ${1}
}

mkdir -p ${BASE_DIR}/out

cat << _EOF_ > ${INCLUDE_FILE}
#ifndef _WSSL_H_
#define _WSSL_H_

_EOF_

cat          ${BASE_DIR}/include/main.h          | include_filter >> ${INCLUDE_FILE}
cat          ${BASE_DIR}/include/version.h       | include_filter >> ${INCLUDE_FILE}
cat          ${BASE_DIR}/include/base.h          | include_filter >> ${INCLUDE_FILE}
cat          ${BASE_DIR}/include/chain.h         | include_filter >> ${INCLUDE_FILE}
include_exec ${BASE_DIR}/include/result.h        | include_filter >> ${INCLUDE_FILE}
cat          ${BASE_DIR}/include/type_epoll.h    | include_filter >> ${INCLUDE_FILE}
cat          ${BASE_DIR}/include/type_server.h   | include_filter >> ${INCLUDE_FILE}
cat          ${BASE_DIR}/include/type_id.h       | include_filter >> ${INCLUDE_FILE}
cat          ${BASE_DIR}/include/type_buffer.h   | include_filter >> ${INCLUDE_FILE}
cat          ${BASE_DIR}/include/type_header.h   | include_filter >> ${INCLUDE_FILE}
include_exec ${BASE_DIR}/include/type_client.h   | include_filter >> ${INCLUDE_FILE}
cat          ${BASE_DIR}/include/type_callback.h | include_filter >> ${INCLUDE_FILE}
cat          ${BASE_DIR}/include/type_wssl.h     | include_filter >> ${INCLUDE_FILE}

echo >> ${INCLUDE_FILE}
cd ${BASE_DIR}/source
for file in $(\ls *.c | sort)
do
  cat ${file} | awk -f ${BASE_DIR}/tool/awk/make_out_function.awk >> ${INCLUDE_FILE}
  echo >> ${INCLUDE_FILE}
done
echo '#endif' >> ${INCLUDE_FILE}

if [ -e ${LIBRARY_ORGIN} ]
then
  cp ${LIBRARY_ORGIN} ${LIBRARY_FILE}
fi
