#!/bin/sh

BASE_DIR=$(dirname $(dirname $(readlink -f ${0})))

DESTINATION="${BASE_DIR}/include/prototype.h"
DESTINATION_NEW="${DESTINATION}.new"

cat << _EOF_ > ${DESTINATION_NEW}
#ifndef _PROTOTYPE_H_
#define _PROTOTYPE_H_

_EOF_

cd ${BASE_DIR}/source
for file in $(\ls *.c | sort)
do
  echo "/* ${file} */" >> ${DESTINATION_NEW}
  cat ${file} | awk -f ${BASE_DIR}/tool/awk/update_prototype.awk >> ${DESTINATION_NEW}
  echo >> ${DESTINATION_NEW}
done
echo '#endif' >> ${DESTINATION_NEW}

if [ ! -e ${DESTINATION} ]
then
  mv ${DESTINATION_NEW} ${DESTINATION}
else
  if diff ${DESTINATION_NEW} ${DESTINATION} > /dev/null
  then
    rm -f ${DESTINATION_NEW}
  else
    mv ${DESTINATION_NEW} ${DESTINATION}
  fi
fi
