#ifndef _CONFIGURATIONS_H_
#define _CONFIGURATIONS_H_

_INCLUDE_BEGIN_

#define WSSL_DEFAULT_SERVER_NAME           ("WSSL-" WSSL_VERSION)
#define WSSL_DEFAULT_BUFFER_SIZE_IN_OCTETS 4096
#define WSSL_DEFAULT_SLEEP_IN_MSECONDS     1000

_INCLUDE_END_

#define SERVER_BACKLOG_SIZE 16
#define EPOLL_EVENTS_SIZE   16

#endif
