#ifndef _CONFIGURATIONS_H_
#define _CONFIGURATIONS_H_

#define SERVER_BACKLOG_SIZE     16
#define EPOLL_EVENTS_SIZE       16
#define EPOLL_SLEEP_IN_MSECONDS 1000
#define BUFFER_SIZE_IN_OCTETS   4096

#endif
