#!/bin/sh

BASE_DIR=$(dirname $(dirname $(readlink -f ${0})))

INCLUDE_FILE="${BASE_DIR}/source/prototype.h"
INCLUDE_FILE_NEW="${INCLUDE_FILE}.new"

cat << _EOF_ > ${INCLUDE_FILE_NEW}
#ifndef _PROTOTYPE_H_
#define _PROTOTYPE_H_

_EOF_

cd ${BASE_DIR}/source
for file in $(\ls *.c | sort)
do
  echo "/* ${file} */" >> ${INCLUDE_FILE_NEW}
  cat ${file} | awk -f ${BASE_DIR}/tools/awk/make_prototype.awk >> ${INCLUDE_FILE_NEW}
  echo >> ${INCLUDE_FILE_NEW}
done
echo '#endif' >> ${INCLUDE_FILE_NEW}

if [ ! -e ${INCLUDE_FILE} ]
then
  mv ${INCLUDE_FILE_NEW} ${INCLUDE_FILE}
else
  if diff ${INCLUDE_FILE_NEW} ${INCLUDE_FILE} > /dev/null
  then
    rm -f ${INCLUDE_FILE_NEW}
  else
    mv ${INCLUDE_FILE_NEW} ${INCLUDE_FILE}
  fi
fi
