#!/bin/sh

BASE_DIR=$(dirname $(dirname $(readlink -f ${0})))

INCLUDE_FILE="${BASE_DIR}/include/version.h"
INCLUDE_FILE_NEW="${INCLUDE_FILE}.new"
JAVASCRIPT_FILE="${BASE_DIR}/html/index.js"
VERSION_FILE="${BASE_DIR}/VERSION"

NOW="$(date +%Y%m%d)"

cat << _EOF_ > ${INCLUDE_FILE_NEW}
#ifndef _VERSION_H_
#define _VERSION_H_

_INCLUDE_BEGIN_

#define WSSL_VERSION "${NOW}"

_INCLUDE_END_

#endif
_EOF_

if [ ! -e ${INCLUDE_FILE} ]
then
  mv ${INCLUDE_FILE_NEW} ${INCLUDE_FILE}
else
  if diff ${INCLUDE_FILE_NEW} ${INCLUDE_FILE} > /dev/null
  then
    rm -f ${INCLUDE_FILE_NEW}
  else
    mv ${INCLUDE_FILE_NEW} ${INCLUDE_FILE}
  fi
fi

cat << _EOF_ > ${JAVASCRIPT_FILE}
var version = '${NOW}';

/* var serverIPV4Name = '185.69.54.116'; */
/* var serverIPV6Name = '[2a02:7b40:b945:3674::1]'; */
var serverIPV4Name = '127.0.0.1';
var serverIPV6Name = '[::1]';
_EOF_

echo ${NOW} > ${VERSION_FILE}
