#!/bin/sh

BASE_DIR=$(dirname $(dirname $(readlink -f ${0})))

INCLUDE_FILE="${BASE_DIR}/include/version.h"
INCLUDE_FILE_NEW="${INCLUDE_FILE}.new"
VERSION_FILE="${BASE_DIR}/VERSION"

NOW="$(date +%Y%m%d)"

cat << _EOF_ > ${INCLUDE_FILE_NEW}
#ifndef _VERSION_H_
#define _VERSION_H_

_INCLUDE_BEGIN_

#define WSSL_VERSION "${NOW}"

_INCLUDE_END_

#endif
_EOF_

if [ ! -e ${INCLUDE_FILE} ]
then
  mv ${INCLUDE_FILE_NEW} ${INCLUDE_FILE}
else
  if diff ${INCLUDE_FILE_NEW} ${INCLUDE_FILE} > /dev/null
  then
    rm -f ${INCLUDE_FILE_NEW}
  else
    mv ${INCLUDE_FILE_NEW} ${INCLUDE_FILE}
  fi
fi

echo ${NOW} > ${VERSION_FILE}
